version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"

services:
  app:
    build: .
    ports:
      - "3000:3000"  # 👈 This line exposes container port 3000 to host
    depends_on:
      - mongo-db

