version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"

services:
  app:
    build: .
    ports:
      - "5000:5000"  # ✅ Map correct port
    depends_on:
      - mongo-db

